### ISSUE TITLE
Notification spam to players

### ISSUE THREAD

**Issue by bsleys** [IsThisMyRealName/too-many-tokens-online#3]
With this module enabled if I as the GM copy and past a token on the map all players get a notification message with the following:

Found modules/pf2e-beginner-box/assets/tokens-bestiary/kobold-warrior.webp

This is an example of copying a Kobold Warrior with it token set to the above mentioned image.  Thus players know when I as the GM add additional NPCs to the map.

**Comment by IsThisMyRealName** [comment]
You are right. Didn't really think about that. I will disable that for the next release.
