### ISSUE TITLE
How to for Pathfinder 1e?

### ISSUE THREAD

**Issue by Terrox** [IsThisMyRealName/too-many-tokens-online#6]
Doesn't seem to work in foundry v11 for pathfinder 1e

**Comment by IsThisMyRealName** [comment]
What exactly does not work? Can you find the macro? If so, do you get an error message?

**Comment by Terrox** [comment]
Added macro to hotbar
Seletected a goblin token
Clicked macro
Dialogue says to choose an actor, with empty input field.

Will screenshot in a few hours

**Comment by IsThisMyRealName** [comment]
Strange. The input field should be a dropdown, where you can select or search for what you want. If all else fails I will release an update later today to add tokens for creatures from the Pathfinder 2e Monster Core (you can see them here: https://toomanytokens.com/index.html?system=pf). Maybe that will help.

**Comment by Terrox** [comment]
Ah so system should be pf?

**Comment by IsThisMyRealName** [comment]
Currently only DND is implemented in the module and _should_ work. But later today I will add another macro and some files, so you can also use pathfinder tokens.

**Comment by Terrox** [comment]
screenshot of unlinked token macro
![image](https://github.com/user-attachments/assets/cf197a87-c00d-4a35-bc69-07296365762f)

**Comment by IsThisMyRealName** [comment]
Can you type in something in the input field? If not, can you check, that the module folder contains a folder "DND" contains links and names.txt?

**Comment by Terrox** [comment]
yes folders have files.
![image](https://github.com/user-attachments/assets/ceae1c5c-8985-4dea-96b7-acc5afe36986)
![image](https://github.com/user-attachments/assets/f211bb21-af60-42b5-8a5d-480b07a1c2bf)
typing into the field does work - I guess I didn't type the right thing and never saw any dropdown matches.
also double-clicking the field works but I didn't know to try because it seems like a standard input field.
I thought it would try to match by token name from the goblin token I selected.
"Select an actor" input field, I thought this meant my actor but I'm not sure what it means. Maybe should be "enter creature type".
It doesn't update the image on the token selected but it does update the parent actor for the token, so next token dragged in is ok. This seems a bit like a bug but maybe is unique to Pathfinder1e on v11 ?
So I think the flow doesn't work in Pathfinder because you'd import a statblock, then drag a token into scene, then apply toomanytokens, but the token images on scene wont change. You cannot apply images to existing scene tokens, only bring new tokens into scene.

**Comment by IsThisMyRealName** [comment]
Ah okay. I will see if I rename some stuff in the next few days to make it easier to use. Also if you update you should find a second macro for tokens for Pathfinder.
For your usecase of creating an actor/statblock, than draging it in a scene and applying toomanytokens you can do that the following way:

1. Drag the tokens you want to the scene.
2. Select the tokens you want to apply toomanytokens to.
![image](https://github.com/user-attachments/assets/f58f42aa-f582-427d-bb0b-e6b9e0cbe218)
3. Execute the macro and select the creaturename you want tokens for.
![image](https://github.com/user-attachments/assets/b348d154-14a0-45d5-befa-3883150318e7)
4. Select the attributes you want for your tokens. (The creature name (here Goblin Warrior) is optional)
![image](https://github.com/user-attachments/assets/697ded0d-32ec-48d4-9470-6738c3e1ccb0)
5. Press the leftmost button (Assign Too-Many-Tokens to selected tokens)
6. The selected tokens will have too-many-tokens applied.
![image](https://github.com/user-attachments/assets/6525427e-7e53-47b1-a128-c4e3b223ffdd)

If you want to apply toomanytokens to every **newly created** token you can press the second button. If you want to apply toomanytokens to every **newly created** token and update the image for the actor you can select the third button.

I hope this helps. If so I will close this issue once I have changed the texts (enter creature type etc.)

**Comment by Terrox** [comment]
Oh I see, I assumed the 3rd option was everything but it says prototype.
Move your last post into the module description as your instructions :)

**Comment by Terrox** [comment]
btw 2.0.0 hasn't filtered through to the forge yet, I guess it takes a while.

**Comment by IsThisMyRealName** [comment]
That was my bad, I screwed up the update and didn't test it correctly i think. Version 2.0.1 should now be online. Thank you for your help and feedback. :)
